export const networkList = [
  {
    id: 1,
    rpc: `https://polygon-mainnet.g.alchemy.com/v2/qgntfG4-Q_3_4C7v6i0wg709xT8_-Fcc`,
    text: "Polygon Mainnet",
    chain: 137,
    symbol: "MATIC",
    explorer: "https://polygonscan.com",
    isAPI: true,
    isAnkr: false,
    isAdded: true,
  },
  {
    id: 1,
    rpc: `https://polygon-mainnet.g.alchemy.com/v2/qgntfG4-Q_3_4C7v6i0wg709xT8_-Fcc`,
    text: "Polygon Mainnet",
    chain: 137,
    symbol: "MATIC",
    explorer: "https://polygonscan.com",
    isAPI: true,
    isAnkr: false,
    isAdded: true,
  },
  {
    id: 2,
    rpc: `https://polygon-mumbai.g.alchemy.com/v2/qgntfG4-Q_3_4C7v6i0wg709xT8_-Fcc`,
    text: "Polygon Testnet",
    chain: 80001,
    symbol: "MATIC",
    explorer: "https://mumbai.polygonscan.com",
    isAPI: true,
    isAnkr: false,
    isAdded: true,
  },
  {
    id: 3,
    rpc: `https://eth-mainnet.g.alchemy.com/v2/qgntfG4-Q_3_4C7v6i0wg709xT8_-Fcc`,
    text: "Ethereum Mainnet",
    chain: 1,
    symbol: "ETH",
    explorer: "https://etherscan.io/",
    isAPI: true,
    isAnkr: false,
    isAdded: true,
  },
  {
    id: 4,
    rpc: `https://eth-goerli.g.alchemy.com/v2/qgntfG4-Q_3_4C7v6i0wg709xT8_-Fcc`,
    text: "Goerli Testnet",
    chain: 5,
    symbol: "ETH",
    explorer: "https://goerli.etherscan.io/",
    isAPI: true,
    isAnkr: false,
    isAdded: true,
  },
  {
    id: 5,
    rpc: ` https://opt-mainnet.g.alchemy.com/v2/qgntfG4-Q_3_4C7v6i0wg709xT8_-Fcc`,
    text: "Optimism Mainnet",
    chain: 10,
    symbol: "ETH",
    explorer: "https://optimistic.etherscan.io/",
    isAPI: true,
    isAnkr: false,
    isAdded: false,
  },
  {
    id: 6,
    rpc: `https://opt-goerli.g.alchemy.com/v2/qgntfG4-Q_3_4C7v6i0wg709xT8_-Fcc`,
    text: "Optimism Testnet",
    chain: 420,
    symbol: "ETH",
    explorer: "https://goerli-optimism.etherscan.io",
    isAPI: true,
    isAnkr: false,
    isAdded: false,
  },
  {
    id: 7,
    rpc: `https://arb-mainnet.g.alchemy.com/v2/qgntfG4-Q_3_4C7v6i0wg709xT8_-Fcc`,
    text: "Arbitrum Mainnet",
    chain: 42161,
    symbol: "ETH",
    explorer: "https://arbiscan.io/",
    isAPI: true,
    isAnkr: false,
    isAdded: false,
  },
  {
    id: 8,
    rpc: `https://arb-goerli.g.alchemy.com/v2/qgntfG4-Q_3_4C7v6i0wg709xT8_-Fcc`,
    text: "Arbitrum Testnet",
    chain: 421613,
    symbol: "ETH",
    explorer: "https://testnet.arbiscan.io/",
    isAPI: true,
    isAnkr: false,
    isAdded: false,
  },
  {
    id: 9,
    rpc: `https://rpc.ankr.com/fantom`,
    text: "Fantom Mainnet",
    chain: 250,
    symbol: "FTM",
    explorer: "https://ftmscan.com/",
    isAPI: true,
    isAnkr: true,
    ankrKeyWord: "fantom",
    isAdded: false,
  },
  {
    id: 10,
    rpc: `https://rpc.ankr.com/fantom_testnet`,
    text: "Fantom Testnet",
    chain: 4002,
    symbol: "FTM",
    explorer: "https://testnet.ftmscan.com/",
    isAPI: false,
    isAnkr: true,
    isAdded: false,
  },
  {
    id: 11,
    rpc: `https://rpc.ankr.com/avalanche`,
    text: "Avalanche Mainnet",
    chain: 43114,
    symbol: "AVAX",
    explorer: "hhttps://snowtrace.io/",
    isAPI: true,
    isAnkr: true,
    ankrKeyWord: "avalanche",
    isAdded: false,
  },
  {
    id: 12,
    rpc: `https://rpc.ankr.com/avalanche_fuji/`,
    text: "Avalanche Testnet",
    chain: 43113,
    symbol: "AVAX",
    explorer: "https://testnet.snowtrace.io/",
    isAPI: false,
    isAnkr: true,
    isAdded: false,
  },
]